package com.gt.regex;

public enum RegexType {
    IN, OUT, NEW, WEIGHTED_IN, WEIGHTED_OUT, MATH, LOGIC_STOW, LOGIC, IF, OPEN_BRACKET, CLOSED_BRACKET, EMPTY, LABEL, BRANCH, NEW_ARRAY, FOR, FOR_ARROW, PRINT
}
